# Simulation Parameters

no_agents : 35
time_units : 300

# Environment Parameters

dimension_x : 300
dimension_y : 300

danger_reduce : 1

env_max_danger : 1
env_max_resource : 1
env_max_resource_gen_rate : 0.1

monolith_motivation : 100
monolith_spawn_chance : 0.05

# Agent Parameters

res_to_invent : 1
invent_to_energy : 1

ag_max_step : 3
ag_max_interact_dist : 40

ag_basic_needs : 0.2 
ag_move_needs : 0.5

invent_fract : 0.5

ag_random_death : 0.001
ag_sight : 80 # space units
ag_max_invent : 2

training_batch : 15
training_skip_steps : 5

colab_bonus : 1 # (0...1)

# Mating parameters

ag_mating_score : 0.5 # (0...1), higher means agents have to have higher acquintance score to mate
ag_blood_relation_thresh : 0.5  # (0...1), higher means closer relativity
ag_compatibility_thresh : 0.5